### ISSUE TITLE
npm run webpack failed after npm install

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/xpring-common-js#116]
I cannot build and run the repo? 

`npm install`
`npm run webpack`

```
Regenerating Protocol Buffers
/Users/denisangell/projects/xrp/xpring-common-js/xpring-common-protocol-buffers/proto: warning: directory does not exist.
/Users/denisangell/projects/xrp/xpring-common-js/xpring-common-protocol-buffers/**/*.proto: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xpring-common-js@1.1.15 webpack: `npm run clean && ./scripts/regenerate_protos.sh && tsc && npx webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xpring-common-js@1.1.15 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/denisangell/.npm/_logs/2019-12-26T17_25_47_547Z-debug.log

```

**Comment by dangell7** [comment]
I have a feeling your issue is that you're embedding repo's inside of other repos. You need to restructure this for scalability as Swift and apple have been very clear about this going forward. It will no longer be an option I believe.

**Comment by dangell7** [comment]
I believe I have solved it with a PR? Let me know if I did something wrong?

**Comment by dangell7** [comment]
https://github.com/xpring-eng/xpring-common-js/pull/117

**Comment by keefertaylor** [comment]
I'm offline for the holidays for the next few days, but wanted to chime in and hopefully get you building. 

If you'd like to build this code, you should see [CONTRIBUTING.md](https://github.com/xpring-eng/xpring-common-js/blob/master/CONTRIBUTING.md) in this repository. 

If you're trying to build the Swift code, you should see [CONTRIBUTING.md](https://github.com/xpring-eng/XpringKit/blob/master/CONTRIBUTING.md) in the XpringKit respository. 

(Aside, if you'd expect to see the build instructions for a repo somewhere other than CONTRIBUTING.md, and I can see if we can make this more obvious). 

To get this repository building, you'll just need to pull down your submodules once. We leave the submodules pinned to a certain commit (and I believe passing `--remote` pulls from head). The right way to do this is just running `git submodule update --init -- recursive` once upon checkout. 

As far as embedding code in a Swift library, we're not embedding modules in the code that we're shipping. Rather, we use git submodules to pull in dependencies (in the form of this repository, and in the form of a protocol buffer repository). I *could* generate and check in this code if there was some reason that submodules didn't work. You may be right that it's worthwhile checking in static resources by default, and we can certainly investigate doing this in the future.

**Comment by dangell7** [comment]
The contributing files definitely helped. I went from error to cloning repos to reading your code. I should have checked there first. They are very clear! 

```
(Aside, if you'd expect to see the build instructions for a repo somewhere other than CONTRIBUTING.md, and I can see if we can make this more obvious).
```

Place those in the README.md, so hopefully it catches the eye maybe? Idk I'm in here now so I can help direct the questions.
